name: Sunblock  codecoverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage/coverage-final.json
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true